workspace:
  base: /srv/eyesofnetwork
  path: notifier

clone:
  git:
    image: plugins/git
    volumes:
      - /etc/hosts:/etc/hosts:ro
pipeline:
  test:
    image: centos:7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/etc/hosts:ro
    commands:
      - chmod +x bin/notifier.pl
      - yum install --assumeyes mariadb mariadb-server
      - mysql_install_db
      - chown -R mysql:mysql /var/lib/mysql
      - /usr/bin/mysqld_safe &
      - yum install --assumeyes perl
      - yum install --assumeyes perl-XML-Simple
      - yum install --assumeyes perl-DBI
      - yum install --assumeyes perl-DBD-MySQL
      - cd docs/db
      - mysql -e "CREATE DATABASE notifier;"
      - mysql notifier < notifier.sql
      - mysql -e "GRANT ALL PRIVILEGES ON notifier.* TO 'notifierSQL'@'localhost' IDENTIFIED BY 'Notifier66';"
      - cd ../..
      - echo '' > log/notifier_send.log
      - $(pwd)/bin/notifier.pl -t host -c $(pwd)/etc/notifier.cfg -r $(pwd)/etc/notifier.rules -T "Mon Dec 18 08:35:12 CEST 1000" -h "localhost" -e "DOWN" -i "127.0.0.1" -n "email" -C "admin" -M "admin@example.org" -O "Host down" -A "LINUX" -G "admins" -X "08:35:28" -Y "10"
      - if [ $? -ne 0 ];then false;fi
      - if [ ! -n $(cat log/notifier_send.log) ]; then false; fi

  notify:
    image: drillster/drone-email
    secrets: [ email_username, email_password ]
    volumes:
      - /etc/hosts:/etc/hosts:ro
    from: no-reply@fricouv.eu
    host: mail.fricouv.local
    recipient:
      - vincent@fricouv.eu
    skip_verify: true
    when:
      status:
        - success
        - failure

